### ISSUE TITLE
Issue with "Shutdown the device after these many missed polls"?

### ISSUE THREAD

**Issue by sumocomputers** [jtburgess/indigo-TP-LInk#10]
I might be misunderstanding how Indigo and the TP-Link Plugin work. Here is what I am finding.

1. I have "Shutdown the device after these many missed polls" set to 99999999999999999999
2. If I unplug the TP-Link HS-110 device from AC Power (which disconnects it from Wi-Fi), within about 30 seconds, Indigo or the TP-Link Plugin disables the device (not sure which)
3. If I plug the TP-Link HS-110 device back into AC Power (which re-connects it to Wi-Fi), within about 30 seconds, the device is back on WiFi network, but the Indigo or the TP-Link plugin never re-enables it.

It would be great if the plugin could do that. Or maybe it should, but isn't currently working? I thought that was what the "Shutdown the device after these many missed polls" feature was supposed to do?

In the meantime, I have documented my workaround in this Indigo Forum thread:

https://forums.indigodomo.com/viewtopic.php?f=134&t=26354&p=212644#p212644

macOS 12.5
Indigo 2022.1.1
TP-Link Plugin 0.9.9

**Comment by jtburgess** [comment]
1. You may have exceeded the maximum integer. I think you exceeded the lifetime of the solar system  anyway 😁

2. The plug-in, probably. If 999999999999 is too big, it may wrap to a negative number, so any missed poll would disable it.  I’ll figure out what is the max, and limit you to that.

3. Definitely a bug.  

Yes, that is exactly what that parameter is intended to do.

-- John

**Comment by sumocomputers** [comment]
@jtburgess Just wondering if you have any target date for the next release?

Thanks,

Chris

**Comment by jtburgess** [comment]
Next year😁.Seriously, I have one unsolved bug.I’ll put some time in next month and see if I can crack it, so maybe February?-- JohnOn Dec 27, 2022, at 1:50 PM, sumocomputers ***@***.***> wrote:﻿
@jtburgess Just wondering if you have any target date for the next release?
Thanks,
Chris

**Comment by jtburgess** [comment]
i've put in a check to limit numeric attributes to 1000000000,
but I don't see the corresponding log message, so I'm not sure its working. Let me know, please

      if int(result[0]) > 1000000000:
        self.logger.info("{} max exceeded (). using 1000000000".format(attribute, result[0]))
        result[0] = '1000000000'

**Comment by sumocomputers** [comment]
I installed the latest and set "Shutdown the device after these many missed polls" to 999999999.

I have tried to simulate a failure by rebooting down the nearby AP with a couple of TP-Link devices, and so far it doesn't seem to be going offline, which is good. I probably need a few more days to see if it holds up.

**Comment by jtburgess** [comment]
please close this issue when you're satisfied. Thanks.

**Comment by sumocomputers** [comment]
I usually see a failure a couple times a week, so I am going to call this good for now.

**Comment by jtburgess** [comment]
Thanks.  Look for a v1.0 release in indigo as soon as I can get to it.-- JohnOn Jan 12, 2023, at 9:55 AM, sumocomputers ***@***.***> wrote:﻿
Closed #10 as completed.
