### ISSUE TITLE
TP-Link KL110 still not working 

### ISSUE THREAD

**Issue by ja422fs** [jtburgess/indigo-TP-LInk#13]
After reinstalling the updated 0.9.9 plugin, I'm getting the following error when I try to add the new KL110 device in Indigo.

   TP-Link Devices Error           Error in plugin execution UiAction:

  File "plugin.py", line 591, in selectTpDevice
type: name 'dev' is not defined

   TP-Link Devices Error           Error in plugin execution UiAction:

  File "plugin.py", line 591, in selectTpDevice
type: name 'dev' is not defined

   TP-Link Devices Error           Error in plugin execution ServerReplacedElem:

  File "/Library/Application Support/Perceptive Automation/Indigo 2022.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/plugin_base.py", line 1379, in device_updated
  File "/Library/Application Support/Perceptive Automation/Indigo 2022.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/plugin_base.py", line 1315, in _dispatch_device_start_comm
  File "plugin.py", line 277, in deviceStartComm
  File "plugin.py", line 152, in getPollClass
  File "/Library/Application Support/Perceptive Automation/Indigo 2022.1/Plugins/TP-Link-Device.indigoPlugin/Contents/Server Plugin/tpl_dimmer_poll.py", line 32, in __init__
type: key deviceId not found in dict

_Originally posted by @ja422fs in https://github.com/jtburgess/indigo-TP-LInk/issues/12#issuecomment-1374575015_

**Comment by jtburgess** [comment]
Got it. That particular code path only happens on new device adds.  So I deleted and re-added my devices to test. Now it works. ... at least for me :-).
I won't be so bold as to close this new one until you agree.

**Comment by ja422fs** [comment]
I reinstalled the Plug-In, but when I go to create a new device, it doesn't assign the correct IP address.
![Screen Shot 2023-01-08 at 4 50 06 PM](https://user-images.githubusercontent.com/30500603/211220975-d3df5b0e-0183-4e18-a03c-6bacbc1b4df3.png)

Here is the Indigo log after restarting the TP-Link plugin.
   Error                           XML Parse Error: not well-formed (invalid token)
   Error                           On character 62 of line number 21.
   Enabling plugin "TP-Link Devices 0.9.9" using API v3.0
   Starting plugin "TP-Link Devices 0.9.9" (pid 66950)
   TP-Link Devices                 Log level set to info
   Started plugin "TP-Link Devices 0.9.9"
   TP-Link Devices                 Polling started for Family Room Lamp - IP Switch@192.168.3.172.
   TP-Link Devices                 Polling started for Living Room Curtains - IP Switch@192.168.3.171.
   TP-Link Devices                 Polling started for Living Room Floor Lamp - IP Switch@192.168.3.174.
   TP-Link Devices                 Polling started for Living Room Lamp 1 - IP Switch@192.168.3.173.
   TP-Link Devices                 Living Room Floor Lamp - IP Switch found set to Off
   TP-Link Devices                 Living Room Lamp 1 - IP Switch found set to Off
   TP-Link Devices                 Family Room Lamp - IP Switch found set to Off
   TP-Link Devices                 Living Room Curtains - IP Switch found set to Off

Jan 8, 2023 at 4:55:44 PM
   TP-Link Devices Error           (plugin.py:getSubType:127): model 'KP125' is not recognised
   TP-Link Devices Error           Error in plugin execution UiAction:

  File "plugin.py", line 591, in selectTpDevice
type: name 'dev' is not defined

   TP-Link Devices Error           Error in plugin execution ServerReplacedElem:

  File "/Library/Application Support/Perceptive Automation/Indigo 2022.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/plugin_base.py", line 1379, in device_updated
  File "/Library/Application Support/Perceptive Automation/Indigo 2022.1/IndigoPluginHost3.app/Contents/Resources/PlugIns/plugin_base.py", line 1315, in _dispatch_device_start_comm
  File "plugin.py", line 277, in deviceStartComm
  File "plugin.py", line 152, in getPollClass
  File "/Library/Application Support/Perceptive Automation/Indigo 2022.1/Plugins/TP-Link-Device.indigoPlugin/Contents/Server Plugin/tpl_dimmer_poll.py", line 32, in __init__
type: key deviceId not found in dict

   TP-Link Devices Error           Error in plugin execution UiValidate:

  File "plugin.py", line 225, in validateDeviceConfigUi
  File "plugin.py", line 336, in initializeDev
type: ('system',)

**Comment by jtburgess** [comment]
Had you added ‘KP125’ before?
It still isn’t in the base code, so the new download didn’t recognize it.

I’ll add it — as a ‘relay’?

-- John

**Comment by ja422fs** [comment]
Yes, I had added the KP125 previously.  It is a HomeKit compatible smart switch – so, I guess we would consider it a relay.  

Is this what is preventing me from adding my smart bulb?

Thanks.
-Jed

**Comment by jtburgess** [comment]
﻿No. I see you hit a couple of errors that I fixed yesterday, so you need to download the latest.It also knows about KP115 and others…😊-- JohnOn Jan 8, 2023, at 5:16 PM, ja422fs ***@***.***> wrote:﻿
Yes, I had added the KP125 previously.  It is a HomeKit compatible smart switch – so, I guess we would consider it a relay.
Is this what is preventing me from adding my smart bulb?
Thanks.
-Jed

**Comment by ja422fs** [comment]
After loading the latest files from last night, I was able to add the KL110 to Indigo.  The on/off works great.  It appears the DimBy and BrightBy commands are not yet supported.  How big of a deal would it be to add those?

Thanks.
-Jed

**Comment by jtburgess** [comment]
😊on #13.DimBy/BrightBy.Are those attributes of the device?Or something to be implemented in indigo?How do you see it working?There is a RampTime attribute — not the same, I realize,  but I use that.-- JohnOn Jan 9, 2023, at 8:43 AM, ja422fs ***@***.***> wrote:﻿
After loading the latest files from last night, I was able to add the KL110 to Indigo.  The on/off works great.  It appears the DimBy and BrightBy commands are not yet supported.  How big of a deal would it be to add those?
Thanks.
-Jed

**Comment by ja422fs** [comment]
The DimBy/BrightenBy commands are Indigo-based and would need to be supported by the Plug-In.  The way it appears to work in Indigo is that a  percentage is provided to the Plug-In for either command.  DimBy 5% reduces the the brightness by 5%.  It works similarly for the BrightenBy commands.

**Comment by jtburgess** [comment]
Ok, It’s only a scripted action, there’s no UI equivalent.I can work on that …. After I get THIS release out.-- JohnOn Jan 9, 2023, at 9:48 AM, ja422fs ***@***.***> wrote:﻿
The DimBy/BrightenBy commands are Indigo-based and would need to be supported by the Plug-In.  The way it appears to work in Indigo is that a  percentage is provided to the Plug-In for either command.  DimBy 5% reduces the the brightness by 5%.  It works similarly for the BrightenBy commands.
