### ISSUE TITLE
Changing the dev.description field (Notes)

### ISSUE THREAD

**Issue by indigodomo** [jtburgess/indigo-TP-LInk#4]
I'd recommend that you not overwrite the description (Notes) field on a device as you do in lines 152-155. Populating it at creation time is OK - but that field is really there for users to keep notes about a device (location, use, etc). Overwriting it every time the device starts up is going to confuse users (like me!) because my changes don't "stick".

**Comment by jtburgess** [comment]
I didn't see this until after I committed.
I'll fix it with the next check-in.

**Comment by jtburgess** [comment]
Jay (I assume). I think this is fixed in the latest code.  
I update dev.description in deviceStartComm(), ONLY if len(dev.description) == 0.
Will that work for you?
Is there a better place to do it?

-- John

**Comment by indigodomo** [comment]
That seems like a reasonable implementation.

**Comment by jtburgess** [comment]
Jay? Matt?
Try downloading tag 0.9.2. I haven’t packaged it for indigo release yet,
But I’d like you to try it out, and give me feedback.
Like, will I need to create a different subtype for colored bulbs,
And what base class should I use?

https://github.com/jtburgess/indigo-TP-LInk/tree/0.9.2

Thanks!

I’m away for a week, then I’ll create a 1.0 release.

-- John

**Comment by indigodomo** [comment]
Hi John,

I'm just wrapping up a move - I'll try it out when I get a chance.

jay

**Comment by jtburgess** [comment]
Resolved in tag 0.9.3
